### ISSUE TITLE
Generation Prompt Reference

### ISSUE THREAD

**Issue by BrenchCC** [KbsdJames/Omni-MATH#2]
Hi, can you please share the prompt you used to generate the answer? I hope to evaluate my model while keeping the prompts consistent, so that I can compare the results on the list.

**Comment by finger1517** [comment]
+1

**Comment by ElhamAhmedian** [comment]
Where is the prompt that was used for the "students" e.g. the other LLMs and not the judge? Also where are the prompts for CoT and PoT python?

**Comment by KbsdJames** [comment]
Thank you for your valuable feedback of our work. We have released the technical report, which contains answers to the questions you raised.
For mathematics-specific models, we strictly followed the prompts as outlined on the model release pages.
For chat models that lack specific instructions on phrasing the mathematical reasoning prompts, we directly input the problem along with a system prompt: “You are an experienced educator in the field of MATHEMATICS.”

For more details, you can refer to https://arxiv.org/pdf/2410.07985.
Thank you once again for your attention of our work.
