### ISSUE TITLE
Using Omni-Judge via VLLM

### ISSUE THREAD

**Issue by zwhe99** [KbsdJames/Omni-MATH#3]
Hi Team, do you have instructions on how to use Omni-Judge via vllm?

**Comment by KbsdJames** [comment]
Hi, we are on it and will release the vllm version soon!

**Comment by KbsdJames** [comment]
Hi, we have updated the `vllm` version for efficient inference.
Please refer to `./Omni-Judge_eval/omni_judge_vllm.sh`.

**Comment by zwhe99** [comment]
Thanks!
